# Generated by Django 2.1 on 2019-01-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
